### ISSUE TITLE
Inport and outport not showing

### ISSUE THREAD

**Issue by HOWTEKNO** [lharri73/PySimlink#12]

**Comment by lharri73** [comment]
Not entirely sure what problem you're encountering. If you're just not seeing the inports and outports in print_all_params, it's because those are not provided in the Simulink model map. 

If you want to change the input to a model, you can change the inport to a constant and change the value of the constant ([usage guide](https://lharri73.github.io/PySimlink/src/howto.html#change-the-value-of-signals)). To get the output of the model, you can just read the signal value of the block emitting the signal going to the outport.
